# Generated by Django 4.2.27 on 2026-03-08 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0013_ownerregistrationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerregistrationrequest',
            name='certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='owner_certificates/'),
        ),
        migrations.AddField(
            model_name='ownerregistrationrequest',
            name='certificate_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
