# Generated by Django 4.2.27 on 2026-03-08 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0014_ownerregistrationrequest_certificate_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerregistrationrequest',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ownerregistrationrequest',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
