# Generated by Django 4.2.27 on 2026-03-08 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0015_ownerregistrationrequest_is_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycdocument',
            name='driving_license_photo',
            field=models.ImageField(blank=True, null=True, upload_to='kyc_documents/'),
        ),
        migrations.AlterField(
            model_name='kycdocument',
            name='secondary_doc_photo',
            field=models.ImageField(blank=True, null=True, upload_to='kyc_documents/'),
        ),
    ]
