# Generated by Django 4.2.27 on 2026-03-08 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0016_alter_kycdocument_driving_license_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycdocument',
            name='driving_license_photo',
            field=models.ImageField(blank=True, null=True, upload_to='kyc/driving_license/'),
        ),
        migrations.AlterField(
            model_name='kycdocument',
            name='secondary_doc_photo',
            field=models.ImageField(blank=True, null=True, upload_to='kyc/secondary_doc/'),
        ),
    ]
