# Generated by Django 4.2.27 on 2026-03-13 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0018_alter_kycdocument_driving_license_photo_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='booking',
            table='booking',
        ),
        migrations.AlterModelTable(
            name='complaint',
            table='complaint',
        ),
        migrations.AlterModelTable(
            name='conversation',
            table='conversation',
        ),
        migrations.AlterModelTable(
            name='favoriteshop',
            table='favorite_shop',
        ),
        migrations.AlterModelTable(
            name='kycdocument',
            table='kyc_document',
        ),
        migrations.AlterModelTable(
            name='message',
            table='message',
        ),
        migrations.AlterModelTable(
            name='notification',
            table='notification',
        ),
        migrations.AlterModelTable(
            name='ownerregistrationrequest',
            table='owner_registration_request',
        ),
        migrations.AlterModelTable(
            name='paymentmethod',
            table='payment_method',
        ),
        migrations.AlterModelTable(
            name='rentalshop',
            table='rental_shop',
        ),
        migrations.AlterModelTable(
            name='review',
            table='review',
        ),
        migrations.AlterModelTable(
            name='savedlocation',
            table='saved_location',
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='user_profile',
        ),
        migrations.AlterModelTable(
            name='usersettings',
            table='user_settings',
        ),
        migrations.AlterModelTable(
            name='vehicle',
            table='vehicle',
        ),
        migrations.AlterModelTable(
            name='vehiclefeature',
            table='vehicle_feature',
        ),
        migrations.AlterModelTable(
            name='vehicleimage',
            table='vehicle_image',
        ),
    ]
