# Generated by Django 4.2.27 on 2026-03-13 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0019_alter_booking_table_alter_complaint_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicleimage',
            name='image_url',
        ),
        migrations.AddField(
            model_name='vehicleimage',
            name='image',
            field=models.ImageField(default='', upload_to='vehicles_img/'),
            preserve_default=False,
        ),
    ]
