# Generated by Django 4.2.27 on 2026-03-13 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0020_remove_vehicleimage_image_url_vehicleimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='owner_img/'),
        ),
    ]
