# Generated by Django 4.2.27 on 2026-03-13 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0021_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalshop',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='shop_img/'),
        ),
    ]
