# Generated by Django 4.2.27 on 2026-03-13 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0022_alter_rentalshop_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalshop',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='owner_img/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='user_img/'),
        ),
    ]
