# Generated by Django 4.2.27 on 2026-03-21 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0025_alter_vehicle_fuel_type_alter_vehicle_seating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='rentals.rentalshop'),
        ),
    ]
