# Generated by Django 4.2.27 on 2026-03-22 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0026_userprofile_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='delivery_option',
            field=models.CharField(choices=[('self_pickup', 'Self Pickup'), ('pickup_service', 'Pickup Service'), ('home_delivery', 'Home Delivery')], default='self_pickup', max_length=15),
        ),
    ]
