# Generated by Django 4.2.27 on 2026-03-13 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_delete_staffcomplaint'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='stafftask',
            table='staff_task',
        ),
    ]
